### ISSUE TITLE
Scaffolding 

### ISSUE THREAD

**Issue by karenpayneoregon** [MicrosoftDocs/ef-core-for-beginners#10]
Dependent on a reader adding pages with entity framework core there is a chance of the tooling to fail with.

`There was an error running the selected code generator: Package restore failed. Rolling back package changes `

I'm sure those who created this realize that it's possible for the NuGet packages for tooling need to be updated as that is what I had to do.

Anyways the above happened to me when creating missing pages for orders but is good after updating the NuGet packages.

- Microsoft.EntityFrameworkCore.Design Version 6.0.9
- Microsoft.EntityFrameworkCore.Tools Version 6.0.9
- Microsoft.VisualStudio.Web.CodeGeneration.Design Version 6.0.9

And sure that others may not run into this issue.

**Comment by CamSoper** [comment]
Sorry I just got around to seeing this. I'll make sure to note this for future versions of the videos.
