### ISSUE TITLE
[BUG]: Line Endings should be LF for installSQLtools.sh

### ISSUE THREAD

**Issue by Snailedlt** [MicrosoftDocs/ef-core-for-beginners#11]
When trying to open the repo in vscode through the `Dev Container: Open Folder in Container...` command, I received an error. Turned out the way to fix the error was to change the line endings of the file (thanks ChatGPT!), which could be done in VSCode by clicking on the `CRLF` symbol in the bottom right corner and selecting `LF` instead of `CRLF`. I'm not sure if this data can be saved in the repo or not, but if it can, it could potensially save others from hours of troubleshooting:
![image](https://user-images.githubusercontent.com/43886029/213533438-c5d374b9-d13a-4382-a7c6-9e71aaa22f48.png)
![image](https://user-images.githubusercontent.com/43886029/213533549-b7a5d34d-d35b-42c8-a4c9-73eafb47f033.png)
![image](https://user-images.githubusercontent.com/43886029/213533634-936b8139-01f9-4d33-a158-b5a21593e0bf.png)

ChatGPT conversation showing the error and ChatGPT's answers: 
https://sharegpt.com/c/Eb5jO4b

**Comment by Snailedlt** [comment]
Maybe we can make git do the opposite of this?
![image](https://user-images.githubusercontent.com/43886029/213534604-7489a57c-5658-4d73-9273-45aacdbc3fa3.png)

**Comment by Snailedlt** [comment]
Aha, you can set up consistent line endings. Documentation here: https://code.visualstudio.com/docs/devcontainers/containers#_working-with-git

**Comment by CamSoper** [comment]
Thanks for this issue! I've run into this before with dev containers, I just forgot to include a `.gitattributes` this time.
