### ISSUE TITLE
Code Tour steps ending with a code block display "Insert Code"

### ISSUE THREAD

**Issue by jongalloway** [MicrosoftDocs/ef-core-for-beginners#4]
Code Tour steps that end with a code will automatically get an "Insert Code" link at the bottom. When I was walking through, I got used to always clicking the Insert Code link when prompted, which results in adding the console output sample to the cs code.

![image](https://user-images.githubusercontent.com/68539/166071261-8248fc4c-2486-4aa0-bc54-037b4d82c245.png)

**Comment by Snailedlt** [comment]
Perhaps some dummy text could be added to those steps that don't require you to insert code?

`.` maybe?

**Comment by CamSoper** [comment]
@Snailedlt I agree, but that's a CodeTour thing for all code fencing.
